# Generated by Django 4.1.4 on 2023-01-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={},
        ),
    ]
