# Generated by Django 4.1.4 on 2023-01-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
