# Generated by Django 4.1.4 on 2023-01-18 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0003_alter_task_author_alter_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelstotask',
            name='label',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Labels',
        ),
        migrations.AddField(
            model_name='labelstotask',
            name='labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='labels.label'),
        ),
        migrations.AlterField(
            model_name='labelstotask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', through='tasks.LabelsToTask', to='labels.label', verbose_name='Метки'),
        ),
    ]
